<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-26T10:13:23 CST" name="JavascriptErrorTests" finished-at="2023-09-26T10:13:28 CST" duration-ms="4862">
    <groups>
    </groups>
    <test started-at="2023-09-26T10:13:23 CST" name="JavascriptErrorTests" finished-at="2023-09-26T10:13:28 CST" duration-ms="4862">
      <class name="com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method,java.lang.String,org.testng.ITestContext)[pri:0, instance:com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests@75d3a5e0]" started-at="2023-09-26T10:13:24 CST" name="setUp" finished-at="2023-09-26T10:13:26 CST" duration-ms="2397" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests.javascriptLoadingPageTest()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@1491344a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="javascriptLoadingPageTest()[pri:0, instance:com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests@75d3a5e0]" started-at="2023-09-26T10:13:26 CST" name="javascriptLoadingPageTest" finished-at="2023-09-26T10:13:28 CST" duration-ms="1594" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Severe error: https://298279967.log.optimizely.com/event?a=298279967&d=298279967&y=false&n=https%3A%2F%2Fthe-internet.herokuapp.com%2F&u=oeu1695744807330r0.7526450927057515&wxhr=true&t=1695744807333&f=298349752,318188263 - Failed to load resource: net::ERR_NAME_NOT_RESOLVED,
Severe error: https://the-internet.herokuapp.com/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found),
Severe error: https://298279967.log.optimizely.com/event?a=298279967&d=298279967&y=false&n=engagement&g=298283957&u=oeu1695744807330r0.7526450927057515&wxhr=true&t=1695744807920&f=298349752,318188263 - Failed to load resource: net::ERR_NAME_NOT_RESOLVED,
Severe error: https://the-internet.herokuapp.com/javascript_error 6:51 Uncaught TypeError: Cannot read properties of undefined (reading 'xyz')]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Severe error: https://298279967.log.optimizely.com/event?a=298279967&d=298279967&y=false&n=https%3A%2F%2Fthe-internet.herokuapp.com%2F&u=oeu1695744807330r0.7526450927057515&wxhr=true&t=1695744807333&f=298349752,318188263 - Failed to load resource: net::ERR_NAME_NOT_RESOLVED,
Severe error: https://the-internet.herokuapp.com/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found),
Severe error: https://298279967.log.optimizely.com/event?a=298279967&d=298279967&y=false&n=engagement&g=298283957&u=oeu1695744807330r0.7526450927057515&wxhr=true&t=1695744807920&f=298349752,318188263 - Failed to load resource: net::ERR_NAME_NOT_RESOLVED,
Severe error: https://the-internet.herokuapp.com/javascript_error 6:51 Uncaught TypeError: Cannot read properties of undefined (reading 'xyz')
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests.javascriptLoadingPageTest(JavascriptErrorTests.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- javascriptLoadingPageTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests@75d3a5e0]" started-at="2023-09-26T10:13:28 CST" name="tearDown" finished-at="2023-09-26T10:13:28 CST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.herokuapp.theinternet.javascripterrortest.JavascriptErrorTests -->
    </test> <!-- JavascriptErrorTests -->
  </suite> <!-- JavascriptErrorTests -->
</testng-results>
